version: '3'
services:
  app:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    environment:
      - DISPLAY_ERRORS
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "8000:80"
    volumes:
      - ${PWD}:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE
    ports:
      - "3306:33060"
      - "33060:33060"
      - "33069:3306"
    volumes:
      - ${PWD}/migrations:/docker-entrypoint-initdb.d