version: '3'
services:
  app:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
    environment:
      - DISPLAY_ERRORS=On
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "8000:80"
    volumes:
      - ${PWD}:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=medine
    ports:
      - "3306:33060"
    volumes:
      - ${PWD}/migrations:/docker-entrypoint-initdb.d