FROM composer as backend

LABEL maintainer="fjmn2001@gmail.com"
LABEL application="medine-hello-world"

WORKDIR /app

COPY . /app/
RUN composer install \
    --ignore-platform-reqs \
    --no-ansi \
    --no-dev \
    --no-interaction \
    --no-scripts

FROM php:8-apache

RUN pecl install xdebug-3.1.1 \
    && docker-php-ext-enable xdebug \
    && docker-php-ext-install pdo pdo_mysql

WORKDIR /app

ENV DISPLAY_ERRORS="On"

COPY --from=backend /app /var/www/html/
COPY php.ini /usr/local/etc/php/

